#!/usr/bin/env php
<?php
/**
 * REG-003 : データは UTF-8 であること
 */

if (! isset($argv[1])) {
    echo 'NG (Missing argument)', PHP_EOL;
    exit(1);
}

$input = $argv[1];

if ($input === null) {
    echo 'NG (Null given.)', PHP_EOL;
    exit(1);
}

// Test
$control = '表示機能テスト'; //UTF-8 検知用テストデータ
$encode  = mb_detect_encoding($input, 'UTF-8', true);

if (false === mb_detect_encoding($input, 'UTF-8', true)) {
    echo 'NG (Bad Encoding)', PHP_EOL;
    exit(1);
}

exit(0); // Test Passed
