#!/usr/bin/env php
<?php
namespace TMC\REG001;
/**
 * REG-001:目視上、同じファイル名が重複しないか検証します。
 */

$msg_help = <<< EOL
Usage: REG-001 [OPTIONS] PATHS

受け取った「改行区切りの文字列」（PATHS）で、目視上同じ行がないか検証します。ファイル名が重複しないかなどの検証に使います。

Options:
  -     検証する文字列（PATHS）を引数でなく標準入力から受け取ります。
Paths:
        検証する文字列（PATHS）を指定します。文字列全体をクォートで囲うのを忘れないようにしてください。
EOL;

const SUCCESS = 0; //終了ステータス：成功
const FAILURE = 1; //終了ステータス：失敗（REGのIDと同じ）

if (! isset($argv[1])) {
    print_help();
    exit(FAILURE);
}

$path_dir_search = isset($argv[1]) ? $argv[1] : '';
$is_input_stdin  = ($path_dir_search === '-') ?: false;

if (! $is_input_stdin && ! is_dir($path_dir_search)) {
    print_error('Not a valid directory path.' . PHP_EOL);
    print_error($path_dir_search . PHP_EOL);
    exit(FAILURE);
}

if ($is_input_stdin) {
    while ($name_file = fgets(STDIN)) {
        if (is_duplicate($name_file)) {
            print_error('Duplicate directory found.' . PHP_EOL);
            print_error($name_file . PHP_EOL);
            exit(FAILURE);
        }
    }
} else {
    $dir = new \DirectoryIterator($path_dir_search);
    foreach ($dir as $file) {
        if (is_duplicate($file->getFileName())) {
            print_error('Duplicate directory found.' . PHP_EOL);
            print_error($name_file . PHP_EOL);
            exit(FAILURE);
        }
    }
}

exit(SUCCESS); // Test Passed

function is_duplicate($string)
{
    static $list=[];

    // 全角スペースのトリム
    $string = mb_trim($string);
    // 大文字と小文字を区別
    $string = mb_strtolower($string);
    // ゼロ幅スペースを削除
    $string = remove_zwsp($string);
    // 配列の添字を固定長
    $hash   = substr(hash('sha256', $string), 0, 15);

    if (isset($list[$hash])) {
        return true;
    }

    $list[$hash] = true;
    return false;
}

function mb_trim($string)
{
    static $chars = "[\\x0-\x20\x7F\xC2\xA0\xE3\x80\x80]";
    return preg_replace("/\A{$chars}++|{$chars}++\z/u", '', $string);
}

function print_error($msg)
{
    fputs(STDERR, addslashes($msg));
}

function print_help(){
    global $msg_help;
    print_error(PHP_EOL . trim($msg_help) . PHP_EOL . PHP_EOL);
}

function remove_zwsp($string)
{
    $string = str_replace('​', '', $string); //見えませんが ZWSP が入っています
    $string = str_replace('&#8203;', '', $string);
    $string = str_replace("\xE2\x80\x8B", '', $string);
    $string = str_replace("\xE2\x80\xAC","", $string);

    return $string;
}
